#!/bin/bash

# Mock omxplayer (only available on Raspberry-Pi) using VLC

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"

    case $key in
        -c|--crop)
        CROP="$2"
        shift # past argument
        shift # past value
        ;;
        -w|--win)
        WINDOW="$2"
        shift # past argument
        shift # past value
        ;;
        -o|--orientation)
        ORIENTATION="$2"
        shift # past argument
        shift # past value
        ;;
        --live)
        LIVE=1
        shift # past argument
        ;;
        *)    # unknown option
        POSITIONAL+=("$1") # save it in an array for later
        shift # past argument
        ;;
    esac
done

set -- "${POSITIONAL[@]}" # restore positional parameters

VLC_OPTIONS="--video-on-top --no-video-deco --no-embedded-video"

if [ ! -z "$WINDOW" ]; then
    IFS=',' read -ra ADDR <<< "$WINDOW"
    if [ ! -z "${ADDR[0]}" ]; then
        X=${ADDR[0]}
        VLC_OPTIONS=$VLC_OPTIONS" --video-x $X"
    fi
    if [ ! -z "${ADDR[1]}" ]; then
        Y=${ADDR[1]}
        VLC_OPTIONS=$VLC_OPTIONS" --video-y $Y"
    fi
    if [ ! -z "${ADDR[2]}" ]; then
        WIDTH=${ADDR[2]}
        VLC_OPTIONS=$VLC_OPTIONS" --width $WIDTH"
    fi
    if [ ! -z "${ADDR[3]}" ]; then
        HEIGHT=${ADDR[3]}
        VLC_OPTIONS=$VLC_OPTIONS" --height $HEIGHT"
    fi
fi

if [ ! -z "$CROP" ]; then
    IFS=',' read -ra ADDR <<< "$CROP"
    if [ ! -z "${ADDR[0]}" ]; then
        VLC_OPTIONS=$VLC_OPTIONS" --croppadd-cropleft ${ADDR[0]}"
    fi
    if [ ! -z "${ADDR[1]}" ]; then
        VLC_OPTIONS=$VLC_OPTIONS" --croppadd-croptop ${ADDR[1]}"
    fi
    if [ ! -z "${ADDR[2]}" ]; then
        cropright=$(($WIDTH-${ADDR[2]}))
        VLC_OPTIONS=$VLC_OPTIONS" --croppadd-cropright $cropright"
    fi
    if [ ! -z "${ADDR[3]}" ]; then
        cropleft=$(($HEIGHT-${ADDR[3]}))
        VLC_OPTIONS=$VLC_OPTIONS" --croppadd-cropbottom $cropleft"
    fi
fi

echo vlc $VLC_OPTIONS "$1"
vlc $VLC_OPTIONS "$1"
