# https://docs.codecov.com/docs/codecov-yaml
# The statuses block nothing unless made required in the branch protection.

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    # Coverage of the lines added or modified by the pull request
    patch:
      default:
        target: 80%

comment:
  layout: "condensed_header, diff, files"
  require_changes: true
