version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    target-branch: "3.x"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: pip
    directories:
      - /
      - /docs
    schedule:
      interval: monthly
