# Labels applied to a pull request from the files it changes.
# Syntax: https://github.com/actions/labeler#match-object

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - 'README.rst'

camera:
  - changed-files:
      - any-glob-to-any-file:
          - 'pibooth/camera/**'
          - 'pibooth/plugins/camera_plugin.py'
          - 'tests/test_camera*.py'
          - 'tests/dslr_diag/**'

printer:
  - changed-files:
      - any-glob-to-any-file:
          - 'pibooth/printer.py'
          - 'pibooth/plugins/printer_plugin.py'
          - 'pibooth/scripts/printer.py'
          - 'tests/test_printer.py'

view:
  - changed-files:
      - any-glob-to-any-file:
          - 'pibooth/view/**'
          - 'pibooth/pictures/**'
          - 'pibooth/fonts/**'
          - 'pibooth/config/menu.py'

plugins:
  - changed-files:
      - any-glob-to-any-file:
          - 'pibooth/plugins/**'

translations:
  - changed-files:
      - any-glob-to-any-file:
          - 'pibooth/language.py'

packaging:
  - changed-files:
      - any-glob-to-any-file:
          - 'setup.py'
          - 'MANIFEST.in'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
